### ISSUE TITLE
Assignment 3 is ready for grading

### ISSUE THREAD

**Issue by dylan-linares-culp** [SES-5215-F2020/dylanculp-quant#3]
[https://github.com/SES-5215-F2020/dylanculp-quant/blob/master/Assignment%203.Rmd](url)
[https://github.com/SES-5215-F2020/dylanculp-quant/blob/master/Assignment-3.html](url)

**Comment by saratepfer** [comment]
Nice job, Dylan. Please find comments below:

- line 12: replace {r} with {r, message = FALSE} to prevent R from printing unnecessary lines of code associated with loading your packages.
- For your two sample t-tests, it is not necessary to report the t value. Instead, I would report the 95% confidence interval for the difference of the means.
- Please add some interpretation for your ANOVA tests.
